# Generated by Django 6.0.3 on 2026-03-23 21:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['next_review']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='definition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='ease_factor',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='example',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='interval',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='phonetic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='source_lang',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='target_lang',
            field=models.CharField(default='es', max_length=10),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='translation',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
