# Generated by Django 6.0.1 on 2026-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_flashcard_options_flashcard_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='example_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='synonyms',
            field=models.TextField(blank=True),
        ),
    ]
