# Generated by Django 6.0.1 on 2026-03-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_flashcard_example_2_flashcard_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='last_quality',
            field=models.IntegerField(default=0),
        ),
    ]
