# Generated by Django 6.0.1 on 2026-03-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_flashcard_last_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='last_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
