# Generated by Django 6.0.1 on 2026-04-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_flashcard_last_review_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
